const questions=Array.isArray(window.ESD_QUESTIONS)?window.ESD_QUESTIONS:[];
const TEST_LENGTH=10;
const $=id=>document.getElementById(id);
let order=[],position=0,initialCorrect=0,retryCorrect=0,wrong=[],isRetry=false,answered=false,name='';

$('startForm').addEventListener('submit',e=>{e.preventDefault();name=$('personName').value.trim();if(!name)return;const available=uniqueQuestionIndexes();if(available.length<TEST_LENGTH){alert(`Der Fragenpool enthält nur ${available.length} unterschiedliche Fragen. Mindestens ${TEST_LENGTH} sind nötig.`);return}startTest(available);});
$('next').addEventListener('click',nextQuestion);
$('restart').addEventListener('click',()=>location.reload());
$('print').addEventListener('click',()=>window.print());
$('download').addEventListener('click',downloadResult);

function random(){if(window.crypto?.getRandomValues){const v=new Uint32Array(1);crypto.getRandomValues(v);return v[0]/4294967296}return Math.random()}
function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function uniqueQuestionIndexes(){const seen=new Set(),indexes=[];questions.forEach((q,i)=>{const key=String(q.q||'').trim().toLocaleLowerCase('de-CH').replace(/\s+/g,' ');if(key&&!seen.has(key)){seen.add(key);indexes.push(i)}});return indexes}
function startTest(available=uniqueQuestionIndexes()){order=shuffle(available).slice(0,TEST_LENGTH);position=0;initialCorrect=0;retryCorrect=0;wrong=[];isRetry=false;$('start').classList.add('hidden');$('quiz').classList.remove('hidden');render()}
function updateCounters(){$('correctText').textContent=isRetry?`Hauptrunde: ${initialCorrect}/${TEST_LENGTH}`:`Richtig: ${initialCorrect}`;$('wrongText').textContent=isRetry?`Falsch: ${wrong.length} · Wiederholung ${position+1}/${order.length}`:`Falsch: ${wrong.length} · Wiederholung am Schluss`}
function render(){answered=false;$('feedback').className='feedback hidden';$('next').classList.add('hidden');const idx=order[position],x=questions[idx];$('topic').textContent=x.topic;$('question').textContent=x.q;$('phaseText').textContent=isRetry?'Wiederholung':'Hauptrunde';$('progressText').textContent=isRetry?`Wiederholung ${position+1} / ${order.length}`:`Frage ${position+1} / ${TEST_LENGTH}`;updateCounters();$('bar').style.width=`${((position+1)/order.length)*100}%`;const box=$('answers');box.innerHTML='';shuffle(x.a.map((text,originalIndex)=>({text,originalIndex}))).forEach((choice,displayIndex)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.dataset.answerIndex=choice.originalIndex;const displayLetter=String.fromCharCode(65+displayIndex),imageLetter=String.fromCharCode(97+choice.originalIndex),img=document.createElement('img');img.src=`assets/${x.id}-${imageLetter}.jpg`;img.alt=`Bild zu Antwort ${displayLetter}`;img.onerror=()=>{img.onerror=null;img.src='assets/platzhalter.jpg'};const wrap=document.createElement('span'),badge=document.createElement('span'),text=document.createElement('span');wrap.className='answer-text';badge.className='answer-letter';badge.textContent=displayLetter;text.textContent=choice.text;wrap.append(badge,text);b.append(img,wrap);b.onclick=()=>choose(choice.originalIndex,b);box.appendChild(b)})}
function choose(originalIndex,button){if(answered)return;answered=true;const idx=order[position],x=questions[idx],buttons=[...$('answers').children];buttons.forEach(b=>b.disabled=true);const correctButton=buttons.find(b=>Number(b.dataset.answerIndex)===x.c);if(correctButton)correctButton.classList.add('correct');const ok=originalIndex===x.c;if(!ok)button.classList.add('wrong');if(isRetry){if(ok)retryCorrect++}else if(ok){initialCorrect++}else{wrong.push(idx)}updateCounters();const f=$('feedback'),strong=document.createElement('strong');f.className=`feedback ${ok?'good':'bad'}`;f.replaceChildren();strong.textContent=ok?'Richtig.':'Nicht richtig.';f.append(strong,document.createElement('br'),document.createTextNode(x.e));$('next').textContent=(position===order.length-1)?(isRetry?'Auswertung':'Runde abschliessen'):'Weiter';$('next').classList.remove('hidden')}
function nextQuestion(){position++;if(position<order.length){render();return}if(!isRetry&&wrong.length){isRetry=true;order=[...wrong];position=0;render();return}finish()}
function finish(){$('quiz').classList.add('hidden');$('result').classList.remove('hidden');const passed=initialCorrect>=8;$('resultTitle').textContent=passed?'Wissensüberprüfung bestanden':'Wissensüberprüfung noch nicht bestanden';$('resultSummary').textContent=passed?`${name}, du hast die erforderliche Punktzahl erreicht.`:`${name}, du hast weniger als 8 Fragen in der Hauptrunde richtig beantwortet. Bitte besprich die offenen Themen und wiederhole den Test.`;$('initialScore').textContent=`${initialCorrect}/${TEST_LENGTH}`;$('retryScore').textContent=wrong.length?`${retryCorrect}/${wrong.length}`:'Keine nötig';const review=$('topicReview');review.innerHTML='<h3>Zusammenfassung</h3>';if(!wrong.length){review.innerHTML+='<p>Alle Themen wurden in der Hauptrunde richtig beantwortet.</p>'}else{wrong.forEach(i=>{const d=document.createElement('div');d.className='review-item';const strong=document.createElement('strong');strong.textContent=questions[i].topic;d.append(strong,document.createElement('br'),document.createTextNode(questions[i].e));review.appendChild(d)})}}
function downloadResult(){const date=new Date(),passed=initialCorrect>=8,topics=wrong.length?wrong.map(i=>`- ${questions[i].topic}`).join('\n'):'- Keine';const text=`ESD – Jährliche Wissensüberprüfung\n\nName: ${name}\nDatum: ${date.toLocaleDateString('de-CH')}\nUhrzeit: ${date.toLocaleTimeString('de-CH')}\nFragenpool: ${questions.length} Fragen, davon ${TEST_LENGTH} zufällig geprüft\nErgebnis Hauptrunde: ${initialCorrect} von ${TEST_LENGTH}\nBestanden: ${passed?'Ja':'Nein'}\nWiederholungsfragen richtig: ${wrong.length?retryCorrect+' von '+wrong.length:'Keine Wiederholung nötig'}\n\nIn der Hauptrunde falsch beantwortete Themen:\n${topics}\n\nUnterschrift Mitarbeitende: __________________________\nUnterschrift/Freigabe: _______________________________\n`;const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ESD_Ergebnis_${name.replace(/[^a-z0-9äöü]+/gi,'_')}_${date.toISOString().slice(0,10)}.txt`;a.click();URL.revokeObjectURL(a.href)}
