let data=JSON.parse(JSON.stringify(Array.isArray(window.ESD_QUESTIONS)?window.ESD_QUESTIONS:[]));
const cards=document.getElementById('cards'),count=document.getElementById('count'),message=document.getElementById('message');
document.getElementById('add').onclick=addQuestion;
document.getElementById('export').onclick=exportQuestions;

function field(labelText,value,oninput,multiline=false){const label=document.createElement('label');label.textContent=labelText;const el=document.createElement(multiline?'textarea':'input');el.value=value;el.addEventListener('input',()=>oninput(el.value));label.appendChild(el);return label}
function render(){cards.innerHTML='';count.textContent=`${data.length} Fragen im Pool`;data.forEach((item,index)=>cards.appendChild(questionCard(item,index)))}
function questionCard(item,index){const card=document.createElement('article');card.className='question-card';const head=document.createElement('div');head.className='card-head';const title=document.createElement('h2');title.textContent=`Frage ${index+1} · ${item.id}`;const del=document.createElement('button');del.className='delete';del.type='button';del.textContent='Frage löschen';del.onclick=()=>{if(confirm(`Frage ${index+1} wirklich löschen?`)){data.splice(index,1);render()}};head.append(title,del);card.appendChild(head);const grid=document.createElement('div');grid.className='grid';grid.append(field('Thema',item.topic,v=>item.topic=v));const qf=field('Frage',item.q,v=>item.q=v,true);qf.className='full';grid.append(qf);const answerWrap=document.createElement('div');answerWrap.className='answers full';item.a.forEach((answer,aIndex)=>{const box=document.createElement('div');box.className='answer-edit';const img=document.createElement('img');const letter=String.fromCharCode(97+aIndex);img.src=`assets/${item.id}-${letter}.jpg`;img.alt=`Bild Antwort ${letter.toUpperCase()}`;img.onerror=()=>{img.onerror=null;img.src='assets/platzhalter.jpg'};const name=document.createElement('div');name.className='filename';name.textContent=`${item.id}-${letter}.jpg`;box.append(img,name,field(`Antwort ${letter.toUpperCase()}`,answer,v=>item.a[aIndex]=v,true));answerWrap.appendChild(box)});grid.appendChild(answerWrap);const correct=document.createElement('label');correct.textContent='Richtige Antwort';const select=document.createElement('select');['A','B','C'].forEach((letter,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`Antwort ${letter}`;o.selected=i===item.c;select.appendChild(o)});select.onchange=()=>item.c=Number(select.value);correct.appendChild(select);grid.append(correct);const explanation=field('Erklärung nach der Antwort',item.e,v=>item.e=v,true);explanation.className='full';grid.append(explanation);card.appendChild(grid);return card}
function addQuestion(){const used=data.map(x=>Number(String(x.id).replace(/\D/g,''))).filter(Number.isFinite),next=Math.max(0,...used)+1,id=`q${String(next).padStart(2,'0')}`;data.push({id,topic:'Neues Thema',q:'Neue Frage eingeben',a:['Antwort A','Antwort B','Antwort C'],c:0,e:'Kurze Erklärung eingeben.'});render();setTimeout(()=>cards.lastElementChild?.scrollIntoView({behavior:'smooth'}),0)}
function validate(){if(data.length<10)return 'Mindestens 10 Fragen sind nötig.';const ids=new Set(),texts=new Set();for(let i=0;i<data.length;i++){const x=data[i],normalized=String(x.q||'').trim().toLocaleLowerCase('de-CH').replace(/\s+/g,' ');if(!x.id||ids.has(x.id))return `Frage ${i+1}: ID fehlt oder ist doppelt.`;ids.add(x.id);if(texts.has(normalized))return `Frage ${i+1}: Dieser Fragetext ist bereits vorhanden.`;texts.add(normalized);if(!x.topic.trim()||!x.q.trim()||!x.e.trim()||x.a.length!==3||x.a.some(a=>!a.trim()))return `Frage ${i+1} ist nicht vollständig.`;if(![0,1,2].includes(Number(x.c)))return `Frage ${i+1}: richtige Antwort fehlt.`}return ''}
function exportQuestions(){const error=validate();if(error){message.textContent=error;return}message.textContent='';const content='window.ESD_QUESTIONS = '+JSON.stringify(data,null,2)+';\n',blob=new Blob([content],{type:'text/javascript;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fragen.js';a.click();URL.revokeObjectURL(a.href);message.style.color='#167447';message.textContent='fragen.js wurde heruntergeladen. Ersetze damit die Datei im Testordner.'}
render();
