window.ESD_QUESTIONS = [
  {id:'q01',topic:'EPA-Eintritt',q:'Du willst eine EPA betreten. Was machst du zuerst?',a:['Ich gehe direkt an meinen Arbeitsplatz.','Ich prüfe meine persönliche ESD-Schutzausrüstung.','Ich prüfe nur meine Schuhe.'],c:1,e:'Vor jedem Eintritt in eine EPA muss die persönliche ESD-Schutzausrüstung an der Prüfstation getestet werden.'},
  {id:'q02',topic:'Prüfung – FAIL',q:'Die Prüfung zeigt FAIL. Was machst du?',a:['Ich messe weiter, bis PASS erscheint.','Ich beginne trotzdem mit der Arbeit.','Ich informiere sofort den Abteilungsleiter oder die Stellvertretung und nehme die Arbeit nicht auf.'],c:2,e:'Bei FAIL muss der Abteilungsleiter oder die Stellvertretung informiert werden. Die Arbeit darf nicht aufgenommen werden.'},
  {id:'q03',topic:'Persönliche Ausrüstung',q:'Was gehört zur persönlichen ESD-Schutzausrüstung?',a:['Schuhe, Arbeitsmantel, Handschuhe und Handgelenkerdungsband','Schuhe, Arbeitsmantel und ESD-Kugelschreiber','Schuhe, Arbeitshose und T-Shirt'],c:0,e:'Zur persönlichen ESD-Schutzausrüstung gehören Schuhe, Arbeitsmantel, Handgelenkerdungsband und Handschuhe.'},
  {id:'q04',topic:'Sicherheitsabstand',q:'Ein Gegenstand mit „NOT ESD-SAFE“ steht 10 cm vom Arbeitsbereich entfernt. Ist das in Ordnung?',a:['Ja.','Nein. Der Sicherheitsabstand von 30 cm wird unterschritten.','Nur wenn der Gegenstand aus Kunststoff ist.'],c:1,e:'Elemente mit „NOT ESD-SAFE“ müssen mindestens 30 cm Abstand zum Arbeitsbereich haben.'},
  {id:'q05',topic:'Transport',q:'Ein ESDS soll die EPA verlassen. Welche Verpackung ist richtig?',a:['Ein rosa Beutel ohne Schirmwirkung.','Eine normale Kunststoffverpackung.','Eine geeignete Verpackung, die zusätzlich gegen elektrostatische Felder und Entladungen abschirmt.'],c:2,e:'Ausserhalb der EPA muss die Verpackung zusätzlich elektrostatische Felder und elektrostatische Entladungen abschirmen, zum Beispiel ein geeigneter silberner Abschirmbeutel.'},
  {id:'q06',topic:'Grundsatz',q:'Was ist ein wichtiger Grundsatz des ESD-Schutzes?',a:['Aufladungen möglichst verhindern und entstandene Aufladungen kontrolliert ableiten.','Elektronische Bauteile möglichst schnell hart erden.','Nur Produktionsanlagen müssen geschützt werden.'],c:0,e:'Aufladungen sollen verhindert werden. Entstandene Aufladungen müssen kontrolliert und sicher abgeleitet werden.'},
  {id:'q07',topic:'Empfindliche Bauteile',q:'Ab welcher Spannung können laut Schulungsunterlage erste Schäden an elektronischen Bauteilen entstehen?',a:['10 V','100 V','1’000 V'],c:1,e:'Erste Schäden an elektronischen Bauteilen können bereits ab 100 V entstehen.'},
  {id:'q08',topic:'Arbeitsplatzkontrolle',q:'Welche Kontrolle gehört zur täglichen Sichtkontrolle?',a:['Prüfen, ob der Arbeitsplatz korrekt am EBP angeschlossen ist.','Die Netzspannung jeder Maschine messen.','Alle Verpackungen täglich austauschen.'],c:0,e:'Die korrekte Verbindung des Arbeitsplatzes mit dem EBP gehört zur täglichen Sichtkontrolle.'},
  {id:'q09',topic:'Ionisator',q:'Was kontrollierst du bei einem vorhandenen Ionisator täglich?',a:['Ob er eingeschaltet und der Luftstrom richtig eingestellt ist.','Nur die Farbe des Gehäuses.','Nichts. Der Ionisator wird nur jährlich kontrolliert.'],c:0,e:'Bei der täglichen Sichtkontrolle wird geprüft, ob der Ionisator eingeschaltet und der Luftstrom richtig eingestellt ist.'},
  {id:'q10',topic:'Luftfeuchtigkeit',q:'Welche Umgebungsbedingung hilft, elektrostatische Aufladungen zu verringern?',a:['Höhere Luftfeuchtigkeit.','Sehr tiefe Luftfeuchtigkeit.','Die Luftfeuchtigkeit hat keinen Einfluss.'],c:0,e:'Höhere Luftfeuchtigkeit verringert die mögliche elektrostatische Aufladung. Trockene Luft erhöht das Risiko.'},
  {id:'q11',topic:'Auspacken von ESDS',q:'Wo darf ein ESDS aus der Schutzverpackung genommen werden?',a:['Ausserhalb der EPA, wenn die Verpackung vorsichtig geöffnet wird.','Nur innerhalb einer EPA.','In jedem sauberen Raum.'],c:1,e:'ESDS dürfen nur innerhalb einer EPA aus der Schutzverpackung genommen werden.'},
  {id:'q12',topic:'Ablagefläche',q:'Wo darf ein ESDS abgelegt werden?',a:['Direkt auf einer blanken Metallfläche.','Auf einer geeigneten ESD-Arbeitsfläche.','Auf einem normalen Karton.'],c:1,e:'ESDS dürfen nicht auf hart geerdeten, zum Beispiel metallischen, Oberflächen abgestellt werden. Eine geeignete ESD-Arbeitsfläche ist richtig.'},
  {id:'q13',topic:'Funktionsnachweis',q:'Wann wird der Funktionsnachweis der persönlichen ESD-Schutzausrüstung eingetragen?',a:['Täglich bei Arbeitsantritt mit Datum und Visum.','Nur wenn die Prüfung FAIL zeigt.','Einmal am Ende der Woche für alle Tage.'],c:0,e:'Der Eintrag mit Datum und Visum erfolgt täglich bei Arbeitsantritt.'}
];
